
import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "./components/navbar/nav";
import Foot from "./components/footer/foot";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Nav />
//         {children}
//         <Foot/>
//       </body>
//     </html>
//   );
// }


export default function RootLayout({ children }){
  return (
    <html lang='en'>
      <body>
        <Nav />
        <main>
          {children}
        </main>
        <Foot />
      </body>
    </html>
  );
}